# Generated by Django 3.1.6 on 2021-06-16 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(default='other', max_length=10)),
                ('dob', models.DateField(blank=True)),
                ('address', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('age', models.CharField(max_length=4)),
                ('gender', models.CharField(default='other', max_length=6)),
                ('experience', models.CharField(max_length=4)),
                ('domain', models.CharField(max_length=30)),
                ('office_number', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_no', models.CharField(max_length=20)),
                ('patient_name', models.CharField(max_length=20)),
                ('doctor_name', models.CharField(max_length=20)),
                ('patient_id', models.CharField(max_length=20)),
                ('doctor_id', models.CharField(max_length=20)),
                ('book_date', models.DateField(blank=True)),
                ('book_slot', models.CharField(max_length=10)),
                ('reason', models.CharField(default='--------', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.CharField(default='General', max_length=40)),
                ('date_of_report', models.DateField(blank=True)),
                ('report_status', models.BooleanField(default=False)),
                ('report_img', models.ImageField(null=True, upload_to='')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.contact')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_visit', models.DateField(blank=True)),
                ('purpose', models.CharField(default='General Check up', max_length=30)),
                ('detail', models.ImageField(null=True, upload_to='')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.contact')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(blank=True)),
                ('time_slot', models.CharField(default='0', max_length=10)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.contact')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.doctor')),
            ],
        ),
    ]
