# Generated by Django 3.1.6 on 2021-06-16 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(blank=True)),
                ('time_slot', models.CharField(default='0', max_length=10)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.contact')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.doctor')),
            ],
        ),
    ]
