# Generated by Django 3.1.6 on 2021-06-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='profile_pic',
            field=models.ImageField(default='null', null=True, upload_to=''),
        ),
    ]
