# Generated by Django 3.1.6 on 2021-06-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20210627_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='picture',
            field=models.ImageField(default='null', null=True, upload_to='doctor_profile'),
        ),
    ]
